ifndef TARGET
TARGET=z1
endif

CONTIKI_PROJECT = accel-demo
#CONTIKI_SOURCEFILES += sht11.c potentiometer-sensor.c
APPS=serial-shell


all: $(CONTIKI_PROJECT)

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
