#---------------------------------------------------------------------------
# A (approximative) translation of the JavaScript generated by
# the script that only logs 'printf'
#---------------------------------------------------------------------------

import java.lang.String

timeout_function = None

def run():
    print "PyCoojaTranslated.run()"
    SEMAPHORE_SIM.acquire()
    SEMAPHORE_SCRIPT.acquire()
    if SHUTDOWN: 
        SCRIPT_KILL()
        return
    if TIMEOUT: 
        SCRIPT_TIMEOUT()
        return

    while True:
        log.log("%s"%time +":"+repr(id)+":"+msg+"\n")
        SCRIPT_SWITCH()
        if SHUTDOWN or TIMEOUT:
            return
        
def SCRIPT_SWITCH():
    global msg
    SEMAPHORE_SIM.release()
    SEMAPHORE_SCRIPT.acquire()
    if SHUTDOWN: SCRIPT_KILL()
    if TIMEOUT: SCRIPT_TIMEOUT()
    msg = java.lang.String(msg)
    node.setMoteMsg(mote, msg)

def SCRIPT_TIMEOUT():
    if timeout_function != None: 
        timeout_function()
    log.log('TEST TIMEOUT\n')
    log.testFailed()
    while not SHUTDOWN:
	SEMAPHORE_SIM.release()
        SEMAPHORE_SCRIPT.acquire()  
    SCRIPT_KILL()

def SCRIPT_KILL():
    SEMAPHORE_SIM.release(100);  
    #raise RuntimeError('test script killed')

def GENERATE_MSG(time, msg):
    log.generateMessage(time, msg)

def write(mote,msg):
    mote.getInterfaces().getLog().writeString(msg); 

#---------------------------------------------------------------------------
